env:
  - DOCKER_COMPOSE_VERSION=1.27.4
os: linux
language: ruby
# dist: xenial # 16
dist: focal # 20

services:
  - docker

before_install:
  # - sudo apt-get upgrade -y
  # - sudo apt-get update -y
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - sudo apt-get update -y
  - sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

script:
  - ls
  - docker version
  - docker-compose version
  - docker-compose up
  - docker-compose stop