language: ruby

services:
  - docker

before_script:
  - echo "Before Script:"
  - docker version
  - docker-compose version
  - docker-compose up -d --build

script:
  - docker-compose exec frontend yarn run start

after_script:
  # - docker-compose stop
  - docker-compose down