language: ruby

services:
  - docker

before_script:
  - echo "Before Script:"
  - docker version
  - docker-compose version

script:
  - docker-compose up --build -d
  # - docker-compose exec chatroom_frontend yarn run start
  # - docker-compose exec chatroom_backend yarn run start

after_success:
  # - docker-compose stop
  - docker-compose down

after_script:
  - bash <(curl -s https://codecov.io/bash) -t 656aa155-20fb-48b6-a47e-fc704e318ddd