env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - ls

  # Extra Docker Compose file for Traefik.
  - |
    if [ "${TEST_DIR}" == "traefik" ]; then
      docker-compose -f traefik.yml up -d
    fi
  - docker-compose up -d
  - docker-compose stop