version: "3.7"

services:
    backend:
        restart: always
        command: "npm run start"
        environment: 
            PORT: "8080"
            FRONTEND: frontend
        build:
            context: "./backend"
        volumes:
            - ./backend/:/app
        networks:
            - gate-tier
            - back-tier

    frontend:
        restart: always
        # command: "yarn run start"
        stdin_open: true
        environment: 
            CI: "true"
            PORT: "80"
            NODE_ENV: "development"
            BASE_URL: ""
        build:
            context: "./frontend"
        volumes:
            - ./frontend/:/app
        networks:
            - gate-tier

    nginx:
        restart: always
        build:
            context: "./nginx"
        networks:
            - gate-tier
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx:/var/log/nginx/
        ports:
            - "9001:80"
            - "9002:8080"

networks:
    gate-tier:
    back-tier:
